#! /bin/sh

case "$OSTYPE" in
[Ll]inux*)
  echo "Compiling for Linux"
  g++ -pipe -mcpu=pentiumpro -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I.. -I../../kmalloc -D_REENTRANT=1 -shared libkmalloc.cpp kmalloc.c -o libkmalloc.so;;
solaris)
  echo "Compiling for Solaris"
  #CC -xildoff -native -noex -xipo=2 -xO5 -mt -DNDEBUG -I. -I.. -D_REENTRANT=1 -G -PIC libkmalloc.cpp -o libkmalloc.so;;
#  g++ -pipe -DNDEBUG -I. -I.. -D_REENTRANT=1 -fPIC -shared libkmalloc.cpp -o libkmalloc.so;;
  gcc -fPIC -pipe -g -I. -I../../heaplayers -D_REENTRANT=1 -c kmalloc.c
#  gcc -fPIC -pipe -mcpu=ultrasparc -O3 -finline-limit=500 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I.. -D_REENTRANT=1 -c kmalloc.c
   g++ -fPIC -pipe -g  -I. -I../../heaplayers -D_REENTRANT=1 -shared libkmalloc.cpp kmalloc.o -o libkmalloc.so;;
#   g++ -fPIC -pipe -mcpu=ultrasparc -O3 -finline-limit=500 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I../../heaplayers -D_REENTRANT=1 -shared libkmalloc.cpp kmalloc.o -o libkmalloc.so;;
#  g++ -pipe -mcpu=ultrasparc -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I.. -D_REENTRANT=1 -shared libkmalloc.cpp -o libkmalloc.so;;
*)
  echo "hmmm"
esac



