#! /bin/sh

case "$OSTYPE" in
[Ll]inux*)
  echo "Compiling for Linux"
  gcc  -pipe -march=pentium4 -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -D_REENTRANT=1 -shared malloc.c -o libptmalloc.so;;
solaris)
  echo "Compiling for Solaris"
  #CC -xildoff -native -noex -xipo=2 -xO5 -mt -DNDEBUG -I. -I.. -D_REENTRANT=1 -G -PIC libptmalloc.cpp -o libptmalloc.so;;
#  g++ -pipe -DNDEBUG -I. -I.. -D_REENTRANT=1 -fPIC -shared libptmalloc.cpp -o libptmalloc.so;;
  gcc -DUSE_MALLOC_LOCK=1 -fPIC -pipe -mcpu=ultrasparc -O3 -finline-limit=5000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I.. -D_REENTRANT=1 -c ptmalloc.c
   g++ -fPIC -pipe -mcpu=ultrasparc -O3 -finline-limit=5000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I../../heaplayers -D_REENTRANT=1 -shared libptmalloc.cpp ptmalloc.o -o libptmalloc.so;;
#  g++ -pipe -mcpu=ultrasparc -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I.. -D_REENTRANT=1 -shared libptmalloc.cpp -o libptmalloc.so;;
*)
  echo "hmmm"
esac



