/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* the namespace of hash_map */
#define HASH_NAMESPACE __gnu_cxx

/* Define to 1 if compiler supports __builtin_stack_pointer */
/* #undef HAVE_BUILTIN_STACK_POINTER */

/* Define to 1 if you have the <conflict-signal.h> header file. */
/* #undef HAVE_CONFLICT_SIGNAL_H */

/* Define to 1 if you have the declaration of `uname', and to 0 if you don't.
   */
#define HAVE_DECL_UNAME 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <execinfo.h> header file. */
#define HAVE_EXECINFO_H 1

/* define if the compiler has hash_map */
#define HAVE_EXT_HASH_MAP 1

/* define if the compiler has hash_set */
#define HAVE_EXT_HASH_SET 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the <grp.h> header file. */
#define HAVE_GRP_H 1

/* define if the compiler has hash_map */
/* #undef HAVE_HASH_MAP */

/* define if the compiler has hash_set */
/* #undef HAVE_HASH_SET */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <libunwind.h> header file. */
/* #undef HAVE_LIBUNWIND_H */

/* Define to 1 if you have the <linux/ptrace.h> header file. */
#define HAVE_LINUX_PTRACE_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define to 1 if you have the `munmap' function. */
#define HAVE_MUNMAP 1

/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES 1

/* define if libc has program_invocation_name */
#define HAVE_PROGRAM_INVOCATION_NAME 1

/* Define if you have POSIX threads libraries and header files. */
#define HAVE_PTHREAD 1

/* Define to 1 if you have the <pwd.h> header file. */
#define HAVE_PWD_H 1

/* Define to 1 if you have the `sbrk' function. */
#define HAVE_SBRK 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if the system has the type `struct mallinfo'. */
#define HAVE_STRUCT_MALLINFO 1

/* Define to 1 if `eip' is member of `struct sigcontext'. */
#define HAVE_STRUCT_SIGCONTEXT_EIP 1

/* Define to 1 if `regs->nip' is member of `struct sigcontext'. */
/* #undef HAVE_STRUCT_SIGCONTEXT_REGS__NIP */

/* Define to 1 if `rip' is member of `struct sigcontext'. */
/* #undef HAVE_STRUCT_SIGCONTEXT_RIP */

/* Define to 1 if `sc_eip' is member of `struct sigcontext'. */
/* #undef HAVE_STRUCT_SIGCONTEXT_SC_EIP */

/* Define to 1 if `sc_ip' is member of `struct sigcontext'. */
/* #undef HAVE_STRUCT_SIGCONTEXT_SC_IP */

/* Define to 1 if `si_faddr' is member of `struct siginfo'. */
/* #undef HAVE_STRUCT_SIGINFO_SI_FADDR */

/* Define to 1 if `uc_mcontext' is member of `struct ucontext'. */
#define HAVE_STRUCT_UCONTEXT_UC_MCONTEXT 1

/* Define to 1 if you have the <syscall.h> header file. */
#define HAVE_SYSCALL_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if compiler supports __thread */
#define HAVE_TLS 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <unwind.h> header file. */
#define HAVE_UNWIND_H 1

/* define if your compiler has __attribute__ */
#define HAVE___ATTRIBUTE__ 1

/* Define to 1 if the system has the type `__int64'. */
/* #undef HAVE___INT64 */

/* prefix where we look for installed files */
#define INSTALL_PREFIX "/usr/local"

/* Name of package */
#define PACKAGE "google-perftools"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "opensource@google.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "google-perftools"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "google-perftools 0.91"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "google-perftools"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.91"

/* printf format code for printing a size_t and ssize_t */
#define PRIdS "zd"

/* printf format code for printing a size_t and ssize_t */
#define PRIuS "zu"

/* printf format code for printing a size_t and ssize_t */
#define PRIxS "zx"

/* Define to necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* the namespace where STL code like vector<> is defined */
#define STL_NAMESPACE std

/* Version number of package */
#define VERSION "0.91"

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
